name: Build on push main

on:
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: npm install
      - name: Build vite app
        run: npm run build

      #   - name: Deploy to AWS S3
      #     uses: aws-actions/configure-aws-credentials@v4
      #     with:
      #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./dist s3://soundssuper.co --delete
